[package]
name = "DES_thermal_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"
num_cpus = "1.13.0"
rustc-hash = "1.1.0"

